/* Kruger Wild — Website · demo data (fictional copy for a real park) */
window.KW_DATA = {
  species: [
    { id: "lion", name: "Lion", latin: "Panthera leo", iucn: "vu", group: "predator", bigFive: true,
      wash: "savanna", icon: "paw-print", activity: "NOCTURNAL · SOCIAL", habitat: "Open savanna",
      blurb: "The apex of the lowveld, living in prides across the open grasslands.",
      long: "Kruger's lions live in prides of up to a dozen, defending territories along the seasonal rivers. Most hunting happens after dark; by day they rest in the shade of marula and knobthorn.",
      weight: "190 kg", count: "~1,600", best: "Dawn", habitats: ["Open savanna", "Riverine"], where: "Central grasslands · Satara to Olifants" },
    { id: "leopard", name: "Leopard", latin: "Panthera pardus", iucn: "vu", group: "predator", bigFive: true,
      wash: "bushveld", icon: "paw-print", activity: "CREPUSCULAR · SOLITARY", habitat: "Riverine forest",
      blurb: "The most elusive of the Big Five — secretive, nocturnal, rarely seen by day.",
      long: "Solitary and supremely adaptable, the leopard hauls its kills into the canopy to keep them from lions and hyenas. The dense riverine thickets of the south offer the best chance of a sighting.",
      weight: "60 kg", count: "~1,000", best: "Dusk", habitats: ["Riverine forest", "Rocky koppies"], where: "Sabie & Sand River corridors" },
    { id: "elephant", name: "African Elephant", latin: "Loxodonta africana", iucn: "en", group: "herbivore", bigFive: true,
      wash: "dawn", icon: "paw-print", activity: "DIURNAL · MATRIARCHAL", habitat: "Mopane woodland",
      blurb: "Keystone of the ecosystem, reshaping the landscape as it feeds.",
      long: "Family herds led by an old matriarch range widely between water and forage. As ecosystem engineers, elephants push over trees and open up woodland, creating habitat for countless other species.",
      weight: "6,000 kg", count: "~31,000", best: "Midday (water)", habitats: ["Mopane woodland", "Riverine"], where: "Throughout · dense in the north" },
    { id: "rhino", name: "White Rhinoceros", latin: "Ceratotherium simum", iucn: "nt", group: "herbivore", bigFive: true,
      wash: "clay", icon: "paw-print", activity: "DIURNAL · GRAZER", habitat: "Open grassland",
      blurb: "A grazing giant under heavy guard against poaching.",
      long: "The square-lipped white rhino grazes short grass on the southern plains. Intensive anti-poaching work is central to its survival, and exact locations are never published.",
      weight: "2,100 kg", count: "Protected", best: "Early morning", habitats: ["Open grassland"], where: "Location withheld for protection" },
    { id: "buffalo", name: "Cape Buffalo", latin: "Syncerus caffer", iucn: "lc", group: "herbivore", bigFive: true,
      wash: "bushveld", icon: "paw-print", activity: "DIURNAL · HERD", habitat: "Floodplains",
      blurb: "Unpredictable and formidable, moving in herds many hundreds strong.",
      long: "Buffalo gather in vast herds near water in the dry season, fragmenting into smaller bachelor groups as the rains spread grazing. They are among the most dangerous animals to encounter on foot.",
      weight: "750 kg", count: "~40,000", best: "Dry season", habitats: ["Floodplains", "Open savanna"], where: "Rivers & dams park-wide" },
    { id: "giraffe", name: "Giraffe", latin: "Giraffa giraffa", iucn: "lc", group: "herbivore", bigFive: false,
      wash: "savanna", icon: "paw-print", activity: "DIURNAL · BROWSER", habitat: "Acacia savanna",
      blurb: "Browsing the acacia canopy no other herbivore can reach.",
      long: "The southern giraffe feeds high in the thorn trees, its long neck and prehensile tongue reaching leaves beyond every competitor. Loose herds drift across the open woodland.",
      weight: "1,200 kg", count: "~9,000", best: "All day", habitats: ["Acacia savanna", "Open woodland"], where: "Common in the central region" },
    { id: "impala", name: "Impala", latin: "Aepyceros melampus", iucn: "lc", group: "herbivore", bigFive: false,
      wash: "savanna", icon: "paw-print", activity: "DIURNAL · HERD", habitat: "Ecotone edges",
      blurb: "The lowveld's most abundant antelope — and the bushveld's fast food.",
      long: "Graceful and astonishingly numerous, impala thrive on the edge between woodland and grassland. They are the staple prey of nearly every large predator in the park.",
      weight: "55 kg", count: "~150,000", best: "All day", habitats: ["Ecotone edges", "Riverine"], where: "Everywhere — the default sighting" },
    { id: "fish-eagle", name: "African Fish Eagle", latin: "Haliaeetus vocifer", iucn: "lc", group: "bird", bigFive: false,
      wash: "dawn", icon: "bird", activity: "DIURNAL · RAPTOR", habitat: "Wetland",
      blurb: "Its ringing call is the unmistakable voice of African water.",
      long: "Perched over rivers and dams, the fish eagle drops in a spectacular talon-first strike. Its yelping duet, thrown back over the shoulder, is the iconic soundtrack of the waterways.",
      weight: "3.5 kg", count: "Resident", best: "Morning", habitats: ["Wetland", "Riverine"], where: "Major rivers & dams" },
    { id: "secretary-bird", name: "Secretary Bird", latin: "Sagittarius serpentarius", iucn: "en", group: "bird", bigFive: false,
      wash: "savanna", icon: "bird", activity: "DIURNAL · TERRESTRIAL", habitat: "Open grassland",
      blurb: "A striding raptor that hunts snakes on foot.",
      long: "Unmistakable on its long legs, the secretary bird stamps prey to death across the open veld. Once common, it is now globally endangered and a prized sighting on the southern plains.",
      weight: "4 kg", count: "Scarce", best: "Mid-morning", habitats: ["Open grassland"], where: "Southern & central plains" },
  ],
  regions: [
    { name: "Southern Rivers", tag: "Sabie · Crocodile", wash: "bushveld", icon: "drop",
      blurb: "Dense riverine bush and the park's richest leopard country." },
    { name: "Central Plains", tag: "Satara · Olifants", wash: "savanna", icon: "sun-horizon",
      blurb: "Open grassland and big-cat territory between two great rivers." },
    { name: "The Far North", tag: "Pafuri · Punda Maria", wash: "dawn", icon: "mountains",
      blurb: "Baobabs, fever-tree forests, and the park's finest birding." },
  ],
};
